### ISSUE TITLE
Add logs for requests

### ISSUE THREAD

**Issue by GCorbel** [sferik/x#1]
For easier debugging, it would be nice to add logs on each request. I think `Net::HTTP#set_debug_output` can be used. A `logger` argument can be passed on initialization of the client and this can be added after the initialization of Net::HTTP in `X::Connection#initialize` :

```
@http_client.set_debug_output(logger)
```

PS: I love the job you did. This gem is very clean. Thanks a lot.

**Comment by sferik** [comment]
Thank you for the feature suggestion and the kind words. I will work on implementing this now.
